# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListGithubUser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '4.8.2'
  	pod 'OHHTTPStubs/Swift'

  # Pods for ListGithubUser

  target 'ListGithubUserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListGithubUserUITests' do
    # Pods for testing
  end

end
